language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
script:
- match=0
  for change in $(git diff --name-only "${TRAVIS_COMMIT_RANGE%%.*}"); do
    if [[ $change = "package.json" ]]; then
      match=1
      break
    fi
  done
  if [[ $match = 0 ]]; then
    echo "'package.json' remained unchanged, not publishing a new version."
  else;
    echo "'package.json' was changed, publishing a new version..."
    yarn global add vsce
    yarn template
    vsce publish -p $PERSONAL_ACCESS_TOKEN
  fi
  exit 0
notifications:
  email: false
