language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn global add vsce
script:
  - |
    GREEN="\033[32;1m"
    RESET="\033[0m"
    match=0
    for change in $(git diff --name-only HEAD~); do
      if [[ $change = "package.json" ]]; then
        match=1
        break
      fi
    done
    if [[ $match = 0 ]]; then
      echo -e "${GREEN}'package.json' remained unchanged, not publishing a new version.${RESET}"
    else
      echo -e "${GREEN}'package.json' was changed, publishing a new version...${RESET}"
      yarn template
      vsce publish -p $PERSONAL_ACCESS_TOKEN
    fi
    exit 0
notifications:
  email: false
if: tag IS blank AND branch = master
