language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn global add vsce
script:
  - |
    green="\033[5;32m"
    reset="\033[0m"
    match=0
    for change in $(git diff --name-only "${TRAVIS_COMMIT_RANGE%%.*}"); do
      if [[ $change = "package.json" ]]; then
        match=1
        break
      fi
    done
    if [[ $match = 0 ]]; then
      echo "${green}'package.json' remained unchanged, not publishing a new version.${reset}"
    else
      echo "${green}'package.json' was changed, publishing a new version...${reset}"
      yarn template
      vsce publish -p $PERSONAL_ACCESS_TOKEN
    fi
    exit 0
notifications:
  email: false
